package org.mate.util;

public enum FitnessFunction {

    BRANCH_COVERAGE,
    BRANCH_MULTI_OBJECTIVE,
    BRANCH_DISTANCE,
    BRANCH_DISTANCE_MULTI_OBJECTIVE,
    LINE_COVERAGE,
    LINE_PERCENTAGE_COVERAGE,
    METHOD_COVERAGE,
    BASIC_BLOCK_LINE_COVERAGE,
    BASIC_BLOCK_BRANCH_COVERAGE,
    BASIC_BLOCK_MULTI_OBJECTIVE,
    NOVELTY;
}
